// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-f7fIPtGhVTyjeejGNaGJtGNTdAqJqTw',
    appId: '1:336444442882:web:119697bdc8bbb4b292da1b',
    messagingSenderId: '336444442882',
    projectId: 'evently-app-5d312',
    authDomain: 'evently-app-5d312.firebaseapp.com',
    storageBucket: 'evently-app-5d312.firebasestorage.app',
    measurementId: 'G-RE7NM3LMJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIx1FWgeBqiNqKt8ZHPb2v5GMs_6Hox58',
    appId: '1:336444442882:android:1794cddecef4a3c792da1b',
    messagingSenderId: '336444442882',
    projectId: 'evently-app-5d312',
    storageBucket: 'evently-app-5d312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8n9Q1nrur4AmjG6_wQUBViR8j2NT-Fgs',
    appId: '1:336444442882:ios:e9ee5bde30007ba992da1b',
    messagingSenderId: '336444442882',
    projectId: 'evently-app-5d312',
    storageBucket: 'evently-app-5d312.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8n9Q1nrur4AmjG6_wQUBViR8j2NT-Fgs',
    appId: '1:336444442882:ios:e9ee5bde30007ba992da1b',
    messagingSenderId: '336444442882',
    projectId: 'evently-app-5d312',
    storageBucket: 'evently-app-5d312.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-f7fIPtGhVTyjeejGNaGJtGNTdAqJqTw',
    appId: '1:336444442882:web:f1b5055af73a35d092da1b',
    messagingSenderId: '336444442882',
    projectId: 'evently-app-5d312',
    authDomain: 'evently-app-5d312.firebaseapp.com',
    storageBucket: 'evently-app-5d312.firebasestorage.app',
    measurementId: 'G-LQ1BG307ZJ',
  );
}
